import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Card from '../components/Card'
import Button from '../components/Button'

export default function MVPDemo() {
  const router = useRouter()
  const { id } = router.query
  const [demoData, setDemoData] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (id) {
      loadDemoData()
    }
  }, [id])

  const loadDemoData = async () => {
    try {
      // Simulate loading demo MVP data
      // In a real scenario, this would fetch from a database
      const mockDemoData = {
        id: id,
        name: "Your MVP Demo",
        description: "This is a live preview of your MVP generated by FounderX",
        features: [
          "User Authentication Demo",
          "Dashboard Interface", 
          "Data Management",
          "Responsive Design",
          "Modern UI Components"
        ],
        techStack: "Next.js + React",
        createdAt: new Date().toISOString(),
        status: "Live Demo"
      }
      
      // Simulate loading delay
      setTimeout(() => {
        setDemoData(mockDemoData)
        setLoading(false)
      }, 1000)
      
    } catch (error) {
      console.error('Error loading demo data:', error)
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center">
        <Card className="max-w-md w-full mx-4">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">Loading Your MVP Demo</h2>
            <p className="text-gray-600">Please wait while we prepare your demo...</p>
          </div>
        </Card>
      </div>
    )
  }

  if (!demoData) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-red-50 to-red-100 flex items-center justify-center">
        <Card className="max-w-md w-full mx-4">
          <div className="text-center">
            <div className="text-6xl mb-4">❌</div>
            <h2 className="text-xl font-semibold text-red-900 mb-2">Demo Not Found</h2>
            <p className="text-red-600 mb-4">Sorry, we couldn't find the demo you're looking for.</p>
            <Button onClick={() => router.push('/mvp-builder')}>
              Create New MVP
            </Button>
          </div>
        </Card>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-100">
      {/* Header */}
      <div className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <div className="flex items-center">
              <button 
                onClick={() => router.back()}
                className="mr-4 p-2 hover:bg-gray-100 rounded-lg transition-colors"
              >
                ← Back
              </button>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">{demoData.name}</h1>
                <p className="text-gray-600">{demoData.description}</p>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <span className="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm font-medium">
                ✅ Live Demo
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Demo Features */}
          <div className="lg:col-span-2">
            <Card title="🎯 Demo Features" className="mb-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {demoData.features.map((feature, index) => (
                  <div key={index} className="flex items-center p-3 bg-white rounded-lg border">
                    <span className="text-green-600 mr-3">✓</span>
                    <span className="text-gray-700">{feature}</span>
                  </div>
                ))}
              </div>
            </Card>

            {/* Interactive Demo Sections */}
            <Card title="🚀 Interactive Demo">
              <div className="space-y-6">
                {/* Login Demo */}
                <div className="border rounded-lg p-6 bg-gray-50">
                  <h3 className="font-semibold text-gray-900 mb-4">User Authentication</h3>
                  <div className="space-y-3">
                    <input 
                      type="email" 
                      placeholder="Enter your email"
                      className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    />
                    <input 
                      type="password" 
                      placeholder="Enter your password"
                      className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    />
                    <Button className="w-full">Sign In</Button>
                  </div>
                </div>

                {/* Dashboard Demo */}
                <div className="border rounded-lg p-6 bg-white">
                  <h3 className="font-semibold text-gray-900 mb-4">Dashboard Interface</h3>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="bg-blue-50 p-4 rounded-lg text-center">
                      <div className="text-2xl font-bold text-blue-600">128</div>
                      <div className="text-sm text-gray-600">Users</div>
                    </div>
                    <div className="bg-green-50 p-4 rounded-lg text-center">
                      <div className="text-2xl font-bold text-green-600">$2.4K</div>
                      <div className="text-sm text-gray-600">Revenue</div>
                    </div>
                    <div className="bg-purple-50 p-4 rounded-lg text-center">
                      <div className="text-2xl font-bold text-purple-600">94%</div>
                      <div className="text-sm text-gray-600">Uptime</div>
                    </div>
                  </div>
                </div>

                {/* Data Management Demo */}
                <div className="border rounded-lg p-6 bg-gray-50">
                  <h3 className="font-semibold text-gray-900 mb-4">Data Management</h3>
                  <div className="overflow-x-auto">
                    <table className="min-w-full bg-white rounded-lg overflow-hidden">
                      <thead className="bg-gray-100">
                        <tr>
                          <th className="px-4 py-2 text-left">Name</th>
                          <th className="px-4 py-2 text-left">Email</th>
                          <th className="px-4 py-2 text-left">Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr className="border-b">
                          <td className="px-4 py-2">John Doe</td>
                          <td className="px-4 py-2">john@example.com</td>
                          <td className="px-4 py-2">
                            <span className="bg-green-100 text-green-800 px-2 py-1 rounded text-xs">
                              Active
                            </span>
                          </td>
                        </tr>
                        <tr className="border-b">
                          <td className="px-4 py-2">Jane Smith</td>
                          <td className="px-4 py-2">jane@example.com</td>
                          <td className="px-4 py-2">
                            <span className="bg-green-100 text-green-800 px-2 py-1 rounded text-xs">
                              Active
                            </span>
                          </td>
                        </tr>
                        <tr>
                          <td className="px-4 py-2">Mike Johnson</td>
                          <td className="px-4 py-2">mike@example.com</td>
                          <td className="px-4 py-2">
                            <span className="bg-yellow-100 text-yellow-800 px-2 py-1 rounded text-xs">
                              Pending
                            </span>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </Card>
          </div>

          {/* Sidebar Info */}
          <div className="space-y-6">
            
            {/* Demo Info */}
            <Card title="📋 Demo Info">
              <div className="space-y-4">
                <div className="flex justify-between">
                  <span className="text-gray-600">ID:</span>
                  <span className="font-mono text-sm">{demoData.id}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Tech Stack:</span>
                  <span className="font-semibold">{demoData.techStack}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Created:</span>
                  <span className="text-sm">{new Date(demoData.createdAt).toLocaleDateString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Status:</span>
                  <span className="bg-green-100 text-green-800 px-2 py-1 rounded text-xs font-medium">
                    {demoData.status}
                  </span>
                </div>
              </div>
            </Card>

            {/* Actions */}
            <Card title="⚡ Actions">
              <div className="space-y-3">
                <Button 
                  onClick={() => window.location.reload()} 
                  className="w-full"
                >
                  🔄 Refresh Demo
                </Button>
                
                <Button 
                  onClick={() => router.push('/mvp-builder')} 
                  variant="outline" 
                  className="w-full"
                >
                  🏗️ Build Another MVP
                </Button>
                
                <Button 
                  onClick={() => {
                    navigator.clipboard.writeText(window.location.href)
                    alert('Demo URL copied to clipboard!')
                  }} 
                  variant="outline" 
                  className="w-full"
                >
                  📋 Copy Demo URL
                </Button>
              </div>
            </Card>

            {/* Notice */}
            <Card title="ℹ️ Notice">
              <div className="text-sm text-gray-600 space-y-2">
                <p>This is a <strong>demo preview</strong> of your MVP. The actual implementation would include:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Full backend functionality</li>
                  <li>Real database integration</li>
                  <li>Payment processing</li>
                  <li>Production-ready security</li>
                  <li>Advanced analytics</li>
                </ul>
                <p className="mt-3 text-blue-600 font-medium">
                  Ready to build the real version? Contact FounderX for full development!
                </p>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}
